name: push
on:
  push:
    branches:
      - master
jobs:
  push:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: dnscontrol push
        uses: koenrh/dnscontrol-action@v3
        env:
          GANDI_API_KEY: ${{ secrets.GANDI_API_KEY }}
        with:
          args: push
          config_file: dnsconfig.js
          creds_file: creds.json
